AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This stack is used for deploying Lambdas in preparation for AWS Cloud Practitioner Course

Resources:
  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/echo/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
