AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This stack is used for deploying S3 resources in preparation for AWS Cloud Practitioner Course

Resources:
  BucketBackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com

  BucketBackupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetReplicationConfiguration
              - s3:ListBucket
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${DemoBucket}"
          - Action:
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${DemoBucket}/*"
          - Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${DemoBucketReplica}/*"
      PolicyName: BucketBackupPolicy
      Roles:
        - !Ref BucketBackupRole

  DemoBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "demo-bucket-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt BucketBackupRole.Arn
        Rules:
          - Destination:
              Bucket: !Sub "arn:aws:s3:::${DemoBucketReplica}"
              StorageClass: STANDARD
            Id: Backup
            Prefix: ""
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  DemoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DemoBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${DemoBucket}/*"
            Principal: "*"

  DemoBucketReplica:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "demo-bucket-replica-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - BucketKeyEnabled: true
      #       ServerSideEncryptionByDefault:
      #         SSEAlgorithm: 'aws:kms'
      #         KMSMasterKeyID: !GetAtt  PostCoderDataBucketKey.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      # WebsiteConfiguration:
      #   IndexDocument: index.html
